In [2]:
import numpy as np
import pandas as pd

## Creating a data frame

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 41],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   41    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

labels = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=labels)

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection and indexing of columns

In [5]:
## Selecting columns

df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [6]:
## Selecting two columns

df2[['Name', 'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

## Creating new columns

In [7]:
df2['Designation'] = ['Doctor', 'Engineer', 'Teacher', 'Pilot']

df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000       Pilot

## How to remove a column

In [8]:
df2.drop('Designation', axis=1, inplace=True) # use inplace true to save it

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df3 = df2

df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df3 = df3.drop('Name', axis=1)

df3

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selecting a row

In [12]:
df4 = df2

In [18]:
df4.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [13]:
df4.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [14]:
df4.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

## Selecting subsets of Rows and Columns

In [15]:
df3

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [16]:
df3.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [19]:
df4.loc[[2,3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

## Conditional Selection

In [ ]:
## I only want to see those people whose age is above 30
print('Above 30- ', )
df2[df['Age']>30]

Below 30-

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
print('Below 30- ')
df2[df2['Age']<30]

Below 30-

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [ ]:
print('Above 30 and city must be paris- ')
df2[(df2['Age']>30) & (df2['City']=='Paris')]

Above 30 and city must be paris-

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [20]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   41    London   85000

In [21]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'David', 'Sophia', 'Michael', 'Emma'],
    'Age': [28, 34, 29, 41, 25, 31, 38, 27],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Department': [
        'IT', 'HR', 'Finance', 'Marketing',
        'IT', 'Sales', 'Finance', 'HR'
    ],
    'Position': [
        'Developer', 'HR Manager', 'Accountant', 'Marketing Manager',
        'Data Analyst', 'Sales Executive', 'Financial Analyst', 'Recruiter'
    ],
    'City': [
        'New York', 'Paris', 'Berlin', 'London',
        'Tokyo', 'Sydney', 'Toronto', 'Dubai'
    ],
    'Country': [
        'USA', 'France', 'Germany', 'UK',
        'Japan', 'Australia', 'Canada', 'UAE'
    ],
    'Experience_Years': [4, 8, 5, 12, 2, 6, 10, 3],
    'Salary': [65000, 70000, 62000, 85000, 58000, 68000, 92000, 60000],
    'Performance_Score': [88, 92, 79, 95, 84, 90, 97, 81],
    'Bonus': [5000, 7000, 4000, 10000, 3000, 6000, 12000, 3500],
    'Remote': [True, False, True, False, True, False, True, False],
    'Joining_Year': [2021, 2017, 2020, 2013, 2023, 2019, 2015, 2022]
}


new_df = pd.DataFrame(data)

new_df

,Employee_ID,Name,Age,Gender,Department,Position,City,Country,Experience_Years,Salary,Performance_Score,Bonus,Remote,Joining_Year
0,101,John,28,Male,IT,Developer,New York,USA,4,65000,88,5000,True,2021
1,102,Anna,34,Female,HR,HR Manager,Paris,France,8,70000,92,7000,False,2017
2,103,Peter,29,Male,Finance,Accountant,Berlin,Germany,5,62000,79,4000,True,2020
3,104,Linda,41,Female,Marketing,Marketing Manager,London,UK,12,85000,95,10000,False,2013
4,105,David,25,Male,IT,Data Analyst,Tokyo,Japan,2,58000,84,3000,True,2023
5,106,Sophia,31,Female,Sales,Sales Executive,Sydney,Australia,6,68000,90,6000,False,2019
6,107,Michael,38,Male,Finance,Financial Analyst,Toronto,Canada,10,92000,97,12000,True,2015
7,108,Emma,27,Female,HR,Recruiter,Dubai,UAE,3,60000,81,3500,False,2022

In [24]:
new_df[(new_df['Experience_Years']>=4)&(new_df['Salary']>70000)]

,Employee_ID,Name,Age,Gender,Department,Position,City,Country,Experience_Years,Salary,Performance_Score,Bonus,Remote,Joining_Year
3,104,Linda,41,Female,Marketing,Marketing Manager,London,UK,12,85000,95,10000,False,2013
6,107,Michael,38,Male,Finance,Financial Analyst,Toronto,Canada,10,92000,97,12000,True,2015