In [2]:
import numpy as np
import pandas as pd

## Creating a data frame

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 41],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   41    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

labels = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=labels)

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection and indexing of columns

In [5]:
## Selecting columns

df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [6]:
## Selecting two columns

df2[['Name', 'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

## Creating new columns

In [7]:
df2['Designation'] = ['Doctor', 'Engineer', 'Teacher', 'Pilot']

df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000       Pilot

## How to remove a column

In [8]:
df2.drop('Designation', axis=1, inplace=True) # use inplace true to save it

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df3 = df2

df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df3 = df3.drop('Name', axis=1)

df3

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selecting a row

In [12]:
df4 = df2

In [13]:
df4.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [14]:
df4.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

## Selecting subsets of Rows and Columns

In [15]:
df3

   Age      City  Salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [16]:
df3.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [17]:
df3.loc[[2,3]][['Name', 'Age']]

KeyError: "['Name'] not in index"

## Conditional Selection

In [ ]:
## I only want to see those people whose age is above 30
print('Above 30- ', )
df2[df['Age']>30]

Below 30-

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
print('Below 30- ')
df2[df2['Age']<30]

Below 30-

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [ ]:
print('Above 30 and city must be paris- ')
df2[(df2['Age']>30) & (df2['City']=='Paris')]

Above 30 and city must be paris-

   Name  Age   City  Salary
1  Anna   34  Paris   70000